# Generated by Django 4.2.7 on 2025-11-13 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('academic', 'Academic'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('competition', 'Competition'), ('other', 'Other')], max_length=50)),
                ('rules', models.TextField(help_text='Event rules and guidelines')),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_team_event', models.BooleanField(default=False)),
                ('team_size', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='event_qr_codes/')),
                ('qr_code_data', models.TextField(blank=True, help_text='QR code data for payment')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('hotness_score', models.FloatField(default=0.0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('total_registrations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event_recommendations',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_verification_code', models.CharField(blank=True, max_length=100)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'db_table': 'registrations',
                'ordering': ['-registered_at'],
            },
        ),
    ]
