# Generated by Django 4.2.7 on 2025-11-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='upi_id',
            field=models.CharField(blank=True, help_text='UPI ID used for transaction', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_verification_code',
            field=models.CharField(blank=True, help_text='UPI Transaction ID', max_length=100),
        ),
    ]
