# Generated by Django 4.2.7 on 2025-11-14 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_registration_upi_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/description for this QR code', max_length=200)),
                ('qr_code_image', models.ImageField(help_text='QR code image file', upload_to='payment_qr_codes/')),
                ('qr_code_data', models.TextField(blank=True, help_text='QR code data (UPI ID, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this QR code is currently in use')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment QR Code',
                'verbose_name_plural': 'Payment QR Codes',
                'db_table': 'payment_qr_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
