# Generated by Django 4.2.7 on 2025-11-14 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_paymentqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_qr_code',
            field=models.ForeignKey(blank=True, help_text='Reusable payment QR code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.paymentqrcode'),
        ),
    ]
