# Generated by Django 4.2.7 on 2025-11-13 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_feedbacks', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('positive_sentiment_count', models.IntegerField(default=0)),
                ('neutral_sentiment_count', models.IntegerField(default=0)),
                ('negative_sentiment_count', models.IntegerField(default=0)),
                ('emotion_distribution', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='events.event')),
            ],
            options={
                'verbose_name_plural': 'Feedback Analytics',
                'db_table': 'feedback_analytics',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('emotion', models.CharField(choices=[('😊', 'Happy'), ('😢', 'Sad'), ('😮', 'Surprised'), ('😍', 'Love'), ('😴', 'Bored'), ('🤔', 'Thoughtful'), ('😎', 'Cool'), ('🙂', 'Neutral')], default='🙂', max_length=10)),
                ('sentiment_score', models.FloatField(blank=True, help_text='AI-generated sentiment score (-1 to 1)', null=True)),
                ('sentiment_label', models.CharField(blank=True, help_text='AI-generated sentiment label', max_length=20)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='events.event')),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='events.registration')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
