"""Utility functions for dashboard and analytics."""
from django.http import HttpResponse
from django.db.models import Count, Sum, Avg
from io import BytesIO
import csv

# Optional imports
try:
    import pandas as pd
    PANDAS_AVAILABLE = True
except ImportError:
    PANDAS_AVAILABLE = False

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

try:
    from openpyxl import Workbook
    OPENPYXL_AVAILABLE = True
except ImportError:
    OPENPYXL_AVAILABLE = False

from events.models import Event, Registration
from feedback.models import Feedback


def generate_analytics_report(events):
    """Generate comprehensive analytics report."""
    data = {
        'total_events': events.count(),
        'total_registrations': Registration.objects.filter(
            event__in=events,
            is_verified=True
        ).count(),
        'total_feedbacks': Feedback.objects.filter(event__in=events).count(),
        'average_rating': Feedback.objects.filter(
            event__in=events
        ).aggregate(Avg('rating'))['rating__avg'] or 0.0,
    }
    return data


def export_to_csv(events, user):
    """Export events data to CSV."""
    # Create response
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="campusnexus_report_{user.username}.csv"'
    
    if PANDAS_AVAILABLE:
        # Use pandas if available
        events_data = []
        for event in events.select_related('created_by'):
            events_data.append({
                'Title': event.title,
                'Department': event.department,
                'Category': event.category,
                'Date': event.event_date.strftime('%Y-%m-%d %H:%M'),
                'Location': event.location,
                'Capacity': event.capacity,
                'Registrations': event.total_registrations,
                'Fee': float(event.fee),
                'Average Rating': event.average_rating,
                'Hotness Score': event.hotness_score,
                'Status': event.status,
                'Created By': event.created_by.username,
            })
        
        df = pd.DataFrame(events_data)
        df.to_csv(response, index=False)
    else:
        # Fallback to manual CSV writing
        writer = csv.writer(response)
        writer.writerow(['Title', 'Department', 'Category', 'Date', 'Location', 'Capacity', 'Registrations', 'Fee', 'Average Rating', 'Hotness Score', 'Status', 'Created By'])
        
        for event in events.select_related('created_by'):
            writer.writerow([
                event.title,
                event.department,
                event.category,
                event.event_date.strftime('%Y-%m-%d %H:%M'),
                event.location,
                event.capacity,
                event.total_registrations,
                float(event.fee),
                event.average_rating,
                event.hotness_score,
                event.status,
                event.created_by.username,
            ])
    
    return response


def export_to_pdf(events, user):
    """Export events data to PDF."""
    if not REPORTLAB_AVAILABLE:
        # Return a simple text response if reportlab not available
        response = HttpResponse(content_type='text/plain')
        response['Content-Disposition'] = f'attachment; filename="campusnexus_report_{user.username}.txt"'
        response.write(f"CampusNexus Report for {user.username}\n")
        response.write("=" * 50 + "\n\n")
        for event in events:
            response.write(f"{event.title} - {event.department}\n")
        return response
    
    buffer = BytesIO()
    p = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Title
    p.setFont("Helvetica-Bold", 16)
    p.drawString(50, height - 50, "CampusNexus Analytics Report")
    p.setFont("Helvetica", 10)
    p.drawString(50, height - 70, f"Generated by: {user.username}")
    p.drawString(50, height - 85, f"Total Events: {events.count()}")

    # Department summary: number of events per department and registrations per event
    from django.db.models import Count, Sum
    y = height - 120
    p.setFont("Helvetica-Bold", 12)
    p.drawString(50, y, "Department Summary:")
    y -= 20

    # Build dept stats
    dept_stats = events.values('department').annotate(
        events_count=Count('id'),
        registrations=Sum('total_registrations')
    ).order_by('-events_count')

    p.setFont("Helvetica", 10)
    for dept in dept_stats:
        if y < 120:
            p.showPage()
            y = height - 50
        dept_line = f"{dept['department']}: {dept['events_count']} events, {dept['registrations'] or 0} registrations"
        p.drawString(50, y, dept_line)
        y -= 15

    # Detailed per-event registration counts (grouped by department)
    p.setFont("Helvetica-Bold", 12)
    if y < 140:
        p.showPage()
        y = height - 50
    p.drawString(50, y, "Per-event Registrations:")
    y -= 20
    p.setFont("Helvetica", 9)
    for event in events.select_related('created_by').order_by('-total_registrations'):
        if y < 100:
            p.showPage()
            y = height - 50
        ev_line = f"{event.title} ({event.department}) - {event.total_registrations} registrations"
        p.drawString(50, y, ev_line[:120])
        y -= 15
    
    p.showPage()
    p.save()
    
    buffer.seek(0)
    response = HttpResponse(buffer.read(), content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="campusnexus_report_{user.username}.pdf"'
    return response

